/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package izv.zaidinvergeles.tienda;

import izv.zaidinvergeles.tienda.Carrito;
import izv.zaidinvergeles.tienda.Menu;
import izv.zaidinvergeles.tienda.Product;
import izv.zaidinvergeles.tienda.mysqlconnector.consultas;
import javax.swing.DefaultListModel;

/**
 *
 * @author alfon
 */
public class Interfaz_Carrito extends javax.swing.JFrame {

    
   private java.util.List<Product> productosEnCarrito = new java.util.ArrayList<>();
    /**
     * Creates new form Interfaz_Carrito
     */
    private Carrito carrito;
    
    private int idCliente;
    private consultas sql = new consultas(); // Añade esta línea
    
    public Interfaz_Carrito() {
        initComponents();
        // Obtenemos el ID del cliente conectado actualmente
        this.idCliente = sql.getIdCliente();
        this.carrito = new Carrito();
        String html = "<html><u>Seguir comprando</u></html>";
        
        // Cargamos los productos del carrito de ESTE cliente
        carrito.getCarrito().addAll(
            sql.obtenerProductosDelCarrito(idCliente) 
        );
        seguirComprando.setText(html);
        mostrarProductosEnCarrito();
        System.out.println("ID Cliente en Interfaz_Carrito: " + idCliente);
    }
    
 private void mostrarProductosEnCarrito() {
    DefaultListModel<String> listModel = new DefaultListModel<>();

    for (Product producto : carrito.getCarrito()) {
        listModel.addElement(producto.getName() + " - " + producto.getPrice() + "€");
    }

    elementos.setModel(listModel);
    // Habilitar la lista para poder seleccionar elementos
    elementos.setEnabled(true);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        carritoArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        elementos = new javax.swing.JList<>();
        seguirComprando = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        Eliminar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setForeground(new java.awt.Color(204, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CARRITO");

        carritoArea.setEnabled(false);

        elementos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        elementos.setEnabled(false);
        jScrollPane1.setViewportView(elementos);

        javax.swing.GroupLayout carritoAreaLayout = new javax.swing.GroupLayout(carritoArea);
        carritoArea.setLayout(carritoAreaLayout);
        carritoAreaLayout.setHorizontalGroup(
            carritoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        carritoAreaLayout.setVerticalGroup(
            carritoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        seguirComprando.setForeground(new java.awt.Color(255, 255, 255));
        seguirComprando.setText("Seguir comprando");
        seguirComprando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seguirComprandoMouseClicked(evt);
            }
        });

        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        Eliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar1.setText("COMPRAR");
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(seguirComprando, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Eliminar))
                                .addComponent(carritoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(Eliminar1)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carritoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seguirComprando)
                    .addComponent(Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seguirComprandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguirComprandoMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);

        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_seguirComprandoMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
        int indiceSeleccionado = elementos.getSelectedIndex();
    
    if (indiceSeleccionado != -1) { // Verificar que se ha seleccionado algo
        // Obtener el producto seleccionado
        Product productoSeleccionado = carrito.getCarrito().get(indiceSeleccionado);
        
        // Mostrar confirmación antes de eliminar
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "¿Estás seguro de eliminar " + productoSeleccionado.getName() + " del carrito?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // Eliminar de la base de datos
            boolean eliminado = sql.eliminarProductoDelCarrito(idCliente, productoSeleccionado.getId());
            
            if (eliminado) {
                // Eliminar del ArrayList local
                carrito.getCarrito().remove(indiceSeleccionado);
                
                // Actualizar la visualización
                mostrarProductosEnCarrito();
                
                // Informar al usuario
                javax.swing.JOptionPane.showMessageDialog(
                        this, 
                        "Producto eliminado del carrito correctamente.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        this, 
                        "No se pudo eliminar el producto del carrito.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Por favor, seleccione un producto para eliminar.",
                "Selección requerida",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_EliminarMouseClicked

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Set the Nimbus look and feel */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            // Instancia del carrito sin pasarle parámetros
            Interfaz_Carrito carritojaja = new Interfaz_Carrito();
            carritojaja.setVisible(true);
            carritojaja.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Eliminar1;
    private javax.swing.JPanel carritoArea;
    private javax.swing.JList<String> elementos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel seguirComprando;
    // End of variables declaration//GEN-END:variables
}
