/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package izv.zaidinvergeles.tienda;

import izv.zaidinvergeles.tienda.mysqlconnector.consultas;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author alfon
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
 
   private java.util.List<Product> listaProductos; // Productos desde BD
    private javax.swing.JPanel panelProductos;

    public Menu() {
        initComponents();
        cargarIconos(); // Llamar a cargarIconos
        cargarProductosDesdeBD(); // Cargar productos desde la base de datos
        mostrarProductos();
    }

    private void cargarIconos() {
    // Cargar icono de usuario
    URL userIconURL = getClass().getResource("/img/usuario.png");
    if (userIconURL != null) {
        jMenu1.setIcon(new javax.swing.ImageIcon(userIconURL));
    } else {
        System.err.println("No se pudo cargar el icono de usuario.");
    }

    // Cargar icono de configuraciones
    URL configIconURL = getClass().getResource("/img/configuraciones.png");
    if (configIconURL != null) {
        jMenuItem3.setIcon(new javax.swing.ImageIcon(configIconURL));
    } else {
        System.err.println("No se pudo cargar el icono de configuraciones.");
    }

    // Cargar icono de carrito
    URL cartIconURL = getClass().getResource("/img/carrito-de-compras.png");
    if (cartIconURL != null) {
        jMenu3.setIcon(new javax.swing.ImageIcon(cartIconURL));
    } else {
        System.err.println("No se pudo cargar el icono del carrito.");
    }

    // Cargar icono de ir al carrito
    URL goToCartIconURL = getClass().getResource("/img/carro-de-la-carretilla.png");
    if (goToCartIconURL != null) {
        ir_Carrito.setIcon(new javax.swing.ImageIcon(goToCartIconURL));
    } else {
        System.err.println("No se pudo cargar el icono de ir al carrito.");
    }

    // Cargar icono de salir
    URL exitIconURL = getClass().getResource("/img/salida.png");
    if (exitIconURL != null) {
        jMenu4.setIcon(new javax.swing.ImageIcon(exitIconURL));
    } else {
        System.err.println("No se pudo cargar el icono de salir.");
    }
}

    private void cargarProductosDesdeBD() {
        listaProductos = new ArrayList<>();
        consultas consulta = new consultas();
        listaProductos = consulta.obtenerProductos(); // Método que debe implementarse en la clase consultas
    }

    private void mostrarProductos() {
        panelProductos = new JPanel();
        panelProductos.setLayout(new GridLayout(0, 1, 10, 10));

        for (Product producto : listaProductos) {
            JPanel panel = new JPanel();
            panel.setLayout(new BorderLayout());

            JLabel lblNombre = new JLabel(producto.toString());
            JButton btnAgregar = new JButton("Añadir al carrito");

            btnAgregar.addActionListener(e -> agregarProductoAlCarrito(producto));

            panel.add(lblNombre, BorderLayout.CENTER);
            panel.add(btnAgregar, BorderLayout.EAST);
            panelProductos.add(panel);
        }

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(new JScrollPane(panelProductos), BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void agregarProductoAlCarrito(Product producto) {
        // Implementar la lógica para agregar el producto al carrito
        // Por ejemplo, puedes usar un método en la clase Carrito para agregar el producto
        System.out.println("Producto agregado al carrito: " + producto.getName());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ir_Carrito = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(0, 250, 0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(300, 50));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu1.setIconTextGap(20);
        jMenu1.setPreferredSize(new java.awt.Dimension(240, 40));
        jMenu1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem3.setText("Configuración");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito-de-compras.png"))); // NOI18N
        jMenu3.setText("Carrito");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu3.setIconTextGap(20);
        jMenu3.setPreferredSize(new java.awt.Dimension(240, 40));
        jMenu3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N

        ir_Carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carro-de-la-carretilla.png"))); // NOI18N
        ir_Carrito.setText("Ir al carrito");
        ir_Carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ir_CarritoActionPerformed(evt);
            }
        });
        jMenu3.add(ir_Carrito);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        jMenu4.setText("Salir");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu4.setIconTextGap(20);
        jMenu4.setPreferredSize(new java.awt.Dimension(240, 40));
        jMenu4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ir_CarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ir_CarritoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        consultas consulta = new consultas();
        Interfaz_Carrito carrito = new Interfaz_Carrito(consulta.getIdCliente());
        carrito.setVisible(true);
    }//GEN-LAST:event_ir_CarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ir_Carrito;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
